// Code generated by "stringer -type=instanceState"; DO NOT EDIT.

package epaxos

import "fmt"

const _instanceState_name = "nonepreAcceptedacceptedcommittedexecuted"

var _instanceState_index = [...]uint8{0, 4, 15, 23, 32, 40}

func (i instanceState) String() string {
	if i < 0 || i >= instanceState(len(_instanceState_index)-1) {
		return fmt.Sprintf("instanceState(%d)", i)
	}
	return _instanceState_name[_instanceState_index[i]:_instanceState_index[i+1]]
}
